version: '3.8'

services:
  db-test:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: very_secure
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node-api:
    depends_on:
      db-test:
        condition: service_started
    image: nodeapi:latest
    build: 
      context: '.'
      dockerfile: './Dockerfile'
    ports:
      - "80:5000"
    env_file:
      - .env

volumes:
  mysql_data:



  

    