version: '3.8'

services:
  db-test:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: very_secure
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node-api:
    depends_on:
      db-test:
        condition: service_started
    image: nodeapi:latest
    build: 
      context: '.'
      dockerfile: './Dockerfile'
    env_file:
      - .env

  nginx-proxy:
    depends_on:
      node-api:
        condition: service_started
    build:
      context: './nginx'
      args:
        NGINX_VERSION: '1.21.6'
        NGINX_HEADERS_MORE_VERSION: '0.37'
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:./etc/nginx/nginx.conf


volumes:
  mysql_data:



  

    